# Setup Frontend Connection to Backend
# This script creates the necessary .env.local file for the frontend

Write-Host "🔗 PureTask - Frontend Connection Setup" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Check if .env.local already exists
if (Test-Path ".env.local") {
    Write-Host "⚠️  .env.local already exists!" -ForegroundColor Yellow
    $overwrite = Read-Host "Do you want to overwrite it? (y/n)"
    if ($overwrite -ne "y") {
        Write-Host "❌ Setup cancelled." -ForegroundColor Red
        exit
    }
}

# Create .env.local file
$envContent = @"
# PureTask Frontend Environment Variables
# Auto-generated by setup-connection.ps1

# Backend API URL (where your Express server runs)
NEXT_PUBLIC_API_URL=http://localhost:4000

# WebSocket URL (for real-time features)
NEXT_PUBLIC_WS_URL=http://localhost:4000

# Frontend base URL
NEXT_PUBLIC_APP_URL=http://localhost:3000

# For production deployment, update these to your deployed URLs:
# NEXT_PUBLIC_API_URL=https://puretask-backend.railway.app
# NEXT_PUBLIC_WS_URL=wss://puretask-backend.railway.app
"@

# Write the file
$envContent | Out-File -FilePath ".env.local" -Encoding UTF8

Write-Host "✅ Created .env.local file!" -ForegroundColor Green
Write-Host ""
Write-Host "📋 Configuration:" -ForegroundColor Cyan
Write-Host "   Frontend: http://localhost:3000" -ForegroundColor White
Write-Host "   Backend:  http://localhost:4000" -ForegroundColor White
Write-Host ""
Write-Host "🚀 Next Steps:" -ForegroundColor Cyan
Write-Host "   1. Start backend:  cd ..\puretask-backend; npm run dev" -ForegroundColor White
Write-Host "   2. Start frontend: npm run dev" -ForegroundColor White
Write-Host "   3. Open browser:   http://localhost:3000" -ForegroundColor White
Write-Host ""
Write-Host "✅ Setup complete!" -ForegroundColor Green

